# Generated by Django 4.1.10 on 2025-11-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
